In [2]:
import tensorflow as tf

In [13]:
#chapter2-1
g1 = tf.Graph()
with g1.as_default():
    a = tf.constant(1)
    b = tf.constant(3)
    c = tf.add(a,b)

In [14]:
with tf.Session(graph=g1) as sess1:
    print(sess1.run(c))

Const:0
4


In [5]:
with tf.Session(graph=g1) as sess2:
    print(sess2.run(c))

4


In [52]:
#chapter2-2
x = tf.constant(4)
y = tf.constant(5)
x1 = tf.constant(4.2)
y1 = tf.constant(5.1)
result_add = tf.add(x,y)
result_subtract = tf.subtract(x,y)
result_multiply = tf.multiply(x,y)
result_divide = tf.divide(x,y)
result_mod = tf.mod(x1,y1)
result_pow = tf.pow(x,y)
result_square = tf.square(x)
result_sqrt = tf.sqrt(x1)

with tf.Session() as sess:
    print(sess.run(result_add))
    print(sess.run(result_subtract))
    print(sess.run(result_multiply))
    print(sess.run(result_divide))
    print(sess.run(result_mod))
    print(sess.run(result_pow))
    print(sess.run(result_square))
    print(sess.run(result_sqrt))

9
-1
20
0.8
4.2
1024
16
2.04939


In [66]:
m = tf.constant([[1,2],[4,5]])
n = tf.constant([[5,6],[7,1]])
result_pow = tf.pow(m,n)
with tf.Session() as sess1:
    print(sess1.run(result_pow))

[[    1    64]
 [16384     5]]


In [17]:
#chapter3
g = tf.Graph()
with g.as_default():
    tf.set_random_seed(1)
    img = tf.random_uniform([10,28,28,3])

In [25]:
#chapter3-1
select_2 = img[1,:,:,:]
with tf.Session(graph=g) as sess:
    print(sess.run(select_2))

[[[0.23643672 0.6406667  0.5484171 ]
  [0.16406047 0.37727487 0.99779356]
  [0.5294342  0.9767134  0.6425712 ]
  ...
  [0.93489444 0.63024235 0.8665024 ]
  [0.8666028  0.6725894  0.8096669 ]
  [0.3966589  0.4415424  0.7160317 ]]

 [[0.04381418 0.19491684 0.19974148]
  [0.60519505 0.93703985 0.48858833]
  [0.574599   0.79322135 0.6849228 ]
  ...
  [0.29457057 0.44304204 0.7210374 ]
  [0.42241645 0.0711087  0.00698876]
  [0.1573813  0.72859144 0.95428336]]

 [[0.9139941  0.09277046 0.76285017]
  [0.29039884 0.6837678  0.53648376]
  [0.6030984  0.53826714 0.9933213 ]
  ...
  [0.24782395 0.32774365 0.9830326 ]
  [0.26645303 0.2615143  0.13805091]
  [0.50397956 0.38233376 0.21479332]]

 ...

 [[0.02650249 0.03378904 0.85801613]
  [0.38010502 0.6547674  0.7013061 ]
  [0.00886011 0.3672911  0.791929  ]
  ...
  [0.475428   0.44775522 0.33677042]
  [0.49176717 0.71025085 0.7886919 ]
  [0.13196278 0.9797127  0.0264051 ]]

 [[0.06688356 0.18537903 0.832752  ]
  [0.23332703 0.5837747  0.49333668]


In [26]:
#chapter3-2
slice_select_2 = tf.slice(img,[1,0,0,0],[1,28,28,3])
with tf.Session(graph=g) as sess:
    print(sess.run(slice_select_2))

[[[[0.23643672 0.6406667  0.5484171 ]
   [0.16406047 0.37727487 0.99779356]
   [0.5294342  0.9767134  0.6425712 ]
   ...
   [0.93489444 0.63024235 0.8665024 ]
   [0.8666028  0.6725894  0.8096669 ]
   [0.3966589  0.4415424  0.7160317 ]]

  [[0.04381418 0.19491684 0.19974148]
   [0.60519505 0.93703985 0.48858833]
   [0.574599   0.79322135 0.6849228 ]
   ...
   [0.29457057 0.44304204 0.7210374 ]
   [0.42241645 0.0711087  0.00698876]
   [0.1573813  0.72859144 0.95428336]]

  [[0.9139941  0.09277046 0.76285017]
   [0.29039884 0.6837678  0.53648376]
   [0.6030984  0.53826714 0.9933213 ]
   ...
   [0.24782395 0.32774365 0.9830326 ]
   [0.26645303 0.2615143  0.13805091]
   [0.50397956 0.38233376 0.21479332]]

  ...

  [[0.02650249 0.03378904 0.85801613]
   [0.38010502 0.6547674  0.7013061 ]
   [0.00886011 0.3672911  0.791929  ]
   ...
   [0.475428   0.44775522 0.33677042]
   [0.49176717 0.71025085 0.7886919 ]
   [0.13196278 0.9797127  0.0264051 ]]

  [[0.06688356 0.18537903 0.832752  ]
   [0.2

In [27]:
#chapter3-3
    #rank is different
#chapter3-4
for i in range(1,5):
    select_1357 = tf.slice(img,[2*i-1,0,0,0],[1,28,28,3])
    with tf.Session(graph=g) as sess:
        print(sess.run(select_1357))

[[[[0.23643672 0.6406667  0.5484171 ]
   [0.16406047 0.37727487 0.99779356]
   [0.5294342  0.9767134  0.6425712 ]
   ...
   [0.93489444 0.63024235 0.8665024 ]
   [0.8666028  0.6725894  0.8096669 ]
   [0.3966589  0.4415424  0.7160317 ]]

  [[0.04381418 0.19491684 0.19974148]
   [0.60519505 0.93703985 0.48858833]
   [0.574599   0.79322135 0.6849228 ]
   ...
   [0.29457057 0.44304204 0.7210374 ]
   [0.42241645 0.0711087  0.00698876]
   [0.1573813  0.72859144 0.95428336]]

  [[0.9139941  0.09277046 0.76285017]
   [0.29039884 0.6837678  0.53648376]
   [0.6030984  0.53826714 0.9933213 ]
   ...
   [0.24782395 0.32774365 0.9830326 ]
   [0.26645303 0.2615143  0.13805091]
   [0.50397956 0.38233376 0.21479332]]

  ...

  [[0.02650249 0.03378904 0.85801613]
   [0.38010502 0.6547674  0.7013061 ]
   [0.00886011 0.3672911  0.791929  ]
   ...
   [0.475428   0.44775522 0.33677042]
   [0.49176717 0.71025085 0.7886919 ]
   [0.13196278 0.9797127  0.0264051 ]]

  [[0.06688356 0.18537903 0.832752  ]
   [0.2

In [50]:
#chapter3-5
select_67 = tf.slice(img,[5,7,7,0],[2,14,14,3])
with tf.Session(graph=g) as sess:
    print(sess.run(select_67))

[[[[0.13691413 0.7961899  0.23560011]
   [0.8427055  0.39532614 0.711962  ]
   [0.69607794 0.81786597 0.7502061 ]
   ...
   [0.39307785 0.46597862 0.921661  ]
   [0.03060198 0.947508   0.50431705]
   [0.33319068 0.70490587 0.06302249]]

  [[0.64700484 0.55882275 0.929826  ]
   [0.14052224 0.67965233 0.26162755]
   [0.6107489  0.51986814 0.4001727 ]
   ...
   [0.41620696 0.9648154  0.55427706]
   [0.5558225  0.720422   0.85429204]
   [0.05395162 0.8503089  0.17544794]]

  [[0.6868249  0.89353323 0.18719923]
   [0.3600676  0.9511949  0.87691796]
   [0.43694496 0.65416634 0.92093563]
   ...
   [0.03887451 0.12154114 0.02275813]
   [0.13490868 0.90507674 0.12138116]
   [0.9603969  0.69834805 0.37301636]]

  ...

  [[0.8708179  0.3860184  0.50923693]
   [0.7153106  0.8052509  0.38405025]
   [0.16225827 0.82440567 0.1454817 ]
   ...
   [0.65843594 0.6796802  0.15165162]
   [0.4109372  0.78448904 0.20809376]
   [0.9091139  0.23375213 0.7518463 ]]

  [[0.254197   0.49465322 0.3302375 ]
   [0.3

In [47]:
#chapter3-6
split_1 = tf.slice(img,[0,0,0,0],[10,28,28,1])
split_2 = tf.slice(img,[0,0,0,1],[10,28,28,1])
split_3 = tf.slice(img,[0,0,0,2],[10,28,28,1])
with tf.Session(graph=g) as sess:
    print(sess.run(split_1))
    print(sess.run(split_2))
    print(sess.run(split_3))

[[[[7.78785586e-01]
   [2.30894327e-01]
   [5.05634069e-01]
   ...
   [2.97357678e-01]
   [8.66402268e-01]
   [7.21464038e-01]]

  [[5.70396066e-01]
   [4.44250107e-02]
   [7.98178792e-01]
   ...
   [1.78476334e-01]
   [6.56885386e-01]
   [5.86949468e-01]]

  [[2.94310570e-01]
   [7.26612568e-01]
   [9.72607136e-01]
   ...
   [3.59869242e-01]
   [1.09508157e-01]
   [9.28915501e-01]]

  ...

  [[8.54026079e-01]
   [6.98262811e-01]
   [8.20209384e-01]
   ...
   [9.25910473e-03]
   [3.83733034e-01]
   [7.80277252e-02]]

  [[2.72139311e-01]
   [4.28068042e-01]
   [8.15427303e-02]
   ...
   [3.81845117e-01]
   [5.91632485e-01]
   [6.74754739e-01]]

  [[5.87010980e-01]
   [2.15796828e-01]
   [9.56021547e-01]
   ...
   [5.59076667e-01]
   [9.03170586e-01]
   [8.52684855e-01]]]


 [[[2.36436725e-01]
   [1.64060473e-01]
   [5.29434204e-01]
   ...
   [9.34894443e-01]
   [8.66602778e-01]
   [3.96658897e-01]]

  [[4.38141823e-02]
   [6.05195045e-01]
   [5.74599028e-01]
   ...
   [2.94570565e-01]
 

In [49]:
#chapter3-7
a = tf.shape(tf.shape(img))
b = tf.rank(tf.shape(img))
c = tf.shape(img)
d = tf.rank(img)
with tf.Session(graph=g) as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

[4]
1
[10 28 28  3]
4


In [10]:
a = tf.constant([[[1, 2], [1, 2]]])
tf.shape(a)
with tf.Session() as sess:
    print(sess.run(tf.shape(a)))

[1 2 2]


In [11]:
a = tf.constant([1,2])
print(a.name)

Const_8:0


In [ ]:
b = 