In [3]:
import tensorflow as tf

In [4]:
with tf.Graph().as_default() as g:
    tmp = tf.constant(1)
    
    for i in range(2,100):
        tmp = tf.add(tmp,i)
        
with tf.Session(graph=g) as sess:
    print(sess.run(tmp))

4950


In [6]:
with tf.Graph().as_default() as g2:
    tmp = tf.constant(1)
    
    for i in range(2,100):
        tmp = tf.add(tmp,i)
        
        
with tf.Session(graph=g2) as sess:
    print(sess.run(tmp))

4950


In [8]:
import tensorflow as tf

In [9]:
a = tf.add(3,5)

In [10]:
print(a)

Tensor("Add:0", shape=(), dtype=int32)


In [11]:
a = tf.add(3,5)
sess = tf.Session()
res = sess.run(a)
print(res)

8


In [12]:
sess.close()

In [14]:
b = tf.add(3,5)
with tf.Session() as sess:
    print(sess.run(b))

8


In [16]:
x = 2
y = 3

op1 = tf.add(x,y)
op2 = tf.multiply(x,y)
op3 = tf.pow(op2,op1)

with tf.Session() as sess:
    res = sess.run(op3)
print(res)

7776


In [2]:
with tf.Graph().as_default() as g:
    tmp = tf.constant(1)
    
    for i in range(2,100):
        tmp = tf.add(tmp,i)
        
with tf.Session(graph=g) as sess:
    print(sess.run(tmp))

4950


In [28]:
a = tf.constant([])
print(a.shape)
print(tf.rank(a))

(0,)
Tensor("Rank:0", shape=(), dtype=int32)


In [30]:
def ones_like(inputs):
    return tf.ones(shape=tf.shape(inputs))

In [31]:
a = tf.constant([[1,2,3],[8,9,7]])
#a = tf.convert_to_tensor([[1,2,3],[8,9,7]])
res_a = ones_like(a)

In [43]:
with tf.Session() as sess:
    print(sess.run(res_a))

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], 
                dtype=tf.float32)


In [35]:
const = tf.constant([[1,2],[3,4],[5,6]])

In [36]:
tf.multiply(const,const)

<tf.Tensor 'Mul_1:0' shape=(3, 2) dtype=int32>

In [37]:
10 * const

<tf.Tensor 'mul_2:0' shape=(3, 2) dtype=int32>

In [50]:
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
with tf.Session() as sess:
    print(sess.run(c))
    print(tf.rank(a))

[[22. 28.]
 [49. 64.]]
Tensor("Rank_1:0", shape=(), dtype=int32)


In [56]:
d = tf.constant(1)
with tf.Session() as sess:
    print(d.shape)
    print(tf.rank(d))

()
Tensor("Rank_2:0", shape=(), dtype=int32)


In [57]:
import numpy as np

In [58]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[1,2],[3,4]])
c = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [59]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
print(b)

[[1 2]
 [3 4]]


In [61]:
print(c)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [62]:
np.concatenate([a,b],axis=0)
#tf.concat

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4]])

In [65]:
np.concatenate([a,c],axis=1)

array([[1, 2, 1, 2, 3],
       [3, 4, 3, 4, 5],
       [5, 6, 5, 6, 7]])

In [66]:
np.r_[a,b]

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4]])

In [67]:
np.c_[a,c]

array([[1, 2, 1, 2, 3],
       [3, 4, 3, 4, 5],
       [5, 6, 5, 6, 7]])

In [68]:
tf.concat([a,c],axis=1)

<tf.Tensor 'concat_1:0' shape=(3, 5) dtype=int64>

In [71]:
a = np.tile(np.arange(28)[: np.newaxis],[28,1]) 
a = a.T
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  7,  7,  

In [72]:
a[5:10][3]

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8])

In [73]:
a[5:10,3]

array([5, 6, 7, 8, 9])

In [74]:
a[5:10][:,3]

array([5, 6, 7, 8, 9])

In [76]:
with tf.Graph().as_default() as g:
    a = tf.constant([1,2])
    with tf.Session() as sess:
        print(g.as_graph_def())
        print(sess.graph)
        print(sess.graph_def)
        print(sess.graph.as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
versions {
  producer: 27
}

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
versions {
  producer: 27
}



In [83]:
a=tf.constant([])
with tf.Session() as sess:
    print(tf.rank(a))
    print(a.shape)

Tensor("Rank_6:0", shape=(), dtype=int32)
(0,)


In [89]:
b=tf.constant([[1], [2], [3]])
with tf.Session() as sess:
    print(tf.rank(b))
    print(b.shape)
    print(sess.run(tf.rank(b)))

Tensor("Rank_12:0", shape=(), dtype=int32)
(3, 1)
2


In [95]:
c=tf.constant([])
with tf.Session() as sess:
    print(c.shape)
    print(sess.run(tf.rank(c)))

(0,)
1


In [96]:
var = tf.Variable(
    [1,2,3],
    collections=[tf.GraphKeys.TRAINABLE_VARIABLES])

In [97]:
var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32_ref>

In [98]:
with tf.Session() as sess:
    sess.run(var.initializer)
    print(sess.run(var))

[1 2 3]


In [109]:
var = tf.Variable(
    1,
    collections=[tf.GraphKeys.TRAINABLE_VARIABLES])
total = tf.Variable(0,collections=([tf.GraphKeys.VARIABLES]))

In [110]:
var_assign = var.assign(tf.add(var,1))
#var_assign = var.assign_add(1)
#var_assign = var.assign_sub(1)
#return operation  fuzhi ji fuzhi's result
total_assign = total.assign(tf.add(total,var))
#return operation

In [112]:
with tf.Session() as sess:
    sess.run([var.initializer,total.initializer])
    #sess.run(tf.global_variables_initializer)chushihua global_variablesjihe bianliang
    #sess.run(tf.local_variable_initializer)local_variable tensorflow neibubianliang  youhua shi de yingzibianliang
    #sess.run(tf.tensor_variable_initializer)
    print(sess.run(total))
    for i in range(100):
        sess.run(var_assign)
        sess.run(total_assign)
    print(sess.run(total))

0
5150


In [114]:
tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
tf.get_collection(tf.GraphKeys)

[]

In [115]:
def zeros(inputs):
    return tf.zeros(shape = inputs.shape)

In [118]:
a = tf.constant([[[1,2],[2,3]],[[5,6],[7,8]]])
res_a = zeros(a)

In [119]:
with tf.Session() as sess:
    print(sess.run(res_a))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [120]:
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
a.dtype

tf.float32

In [124]:
a = tf.constant([[1, 2, 3], [4, 5, 6]],dtype=tf.complex64)
a.dtype

tf.complex64

In [130]:
b = tf.constant([[1.0,2.0],[3.0,4.0]],name = 'b')
print(b.dtype)
print(b.shape)
print(b.get_shape())
print(b.get_shape().as_list())

<dtype: 'float32'>
(2, 2)
(2, 2)
[2, 2]


In [131]:
b = tf.constant(2+3j)
print(b.dtype)

<dtype: 'complex128'>


In [9]:
#在一个notebook文件中构建一张图，实现两个数的加法操作，
#并在两个不同的会话中执行图

with tf.Graph().as_default() as g:
    a = tf.add(1,2)
with tf.Session(graph=g) as sess1:
    print(sess1.run(a))
with tf.Session(graph=g) as sess2:
    print(sess2.run(a))

3
3


In [10]:
a = tf.constant([1, 2, 3], dtype=tf.float64)

In [11]:
b = tf.constant([1, 2, 3], dtype=tf.complex64)

In [14]:
c = tf.constant([1, [2, 3]])

ValueError: setting an array element with a sequence.