In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [4]:
const = tf.constant([1,2,3])

In [18]:
const

<tf.Tensor: id=1, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
print(const)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [16]:
res = tf.multiply(const,const)
res

<tf.Tensor: id=16, shape=(3,), dtype=int32, numpy=array([1, 4, 9], dtype=int32)>

In [7]:
const.numpy()

array([1, 2, 3], dtype=int32)

In [8]:
import numpy as np

In [32]:
from PIL import Image

ImportError: No module named 'PIL'

In [10]:
img = tf.random_uniform(
[128,128,3],maxval = 255,dtype=tf.int32)
img = tf.cast(img,tf.uint8)

In [11]:
r = iter(tf.range(0))

In [13]:
next(r)

StopIteration: 

In [19]:
a = tf.constant(10)
b = np.array(5)

In [20]:
a

<tf.Tensor: id=20, shape=(), dtype=int32, numpy=10>

In [21]:
b

array(5)

In [31]:
print(b)

5


In [24]:
tf_res = tf.multiply(a,b)
np_res = np.multiply(a,b)

In [27]:
tf_res

<tf.Tensor: id=26, shape=(), dtype=int32, numpy=50>

In [28]:
print(tf_res)

tf.Tensor(50, shape=(), dtype=int32)


In [29]:
np_res

50

In [30]:
print(np_res)

50


In [34]:
tf.random_uniform??

In [38]:
m = tf.random_uniform(
[5,2,3],maxval = 100,dtype=tf.int32)
m

<tf.Tensor: id=43, shape=(5, 2, 3), dtype=int32, numpy=
array([[[12,  1, 38],
        [46, 45, 60]],

       [[34, 90, 85],
        [80, 65, 99]],

       [[11, 51, 91],
        [28, 58, 85]],

       [[60, 25, 25],
        [83, 33,  6]],

       [[21, 98, 49],
        [14, 66, 93]]], dtype=int32)>

In [39]:
tf.cast??
#Casts a tensor to a new type

In [40]:
x = tf.constant([1.2,3.8])
x

<tf.Tensor: id=45, shape=(2,), dtype=float32, numpy=array([1.2, 3.8], dtype=float32)>

In [42]:
tf.cast(x,tf.uint8)

<tf.Tensor: id=49, shape=(2,), dtype=uint8, numpy=array([1, 3], dtype=uint8)>

In [43]:
var = tf.get_variable('var',shape=[])
print(var)

<tf.Variable 'var:0' shape=() dtype=float32, numpy=0.08758032>


In [44]:
import tensorflow.contrib.eager as tfe

In [45]:
var = tfe.Variable(20)
print(var)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


In [46]:
tf.constant(0) == 0

False

In [47]:
tf.constant(0) <= 0

<tf.Tensor: id=78, shape=(), dtype=bool, numpy=True>

In [49]:
print(tf.constant(0) >= 0)

tf.Tensor(True, shape=(), dtype=bool)


In [50]:
int(tf.constant(0)) == 0

True

In [51]:
tf.equal(tf.constant(0),0)

<tf.Tensor: id=88, shape=(), dtype=bool, numpy=True>

In [52]:
tf.constant(0).numpy() == 0

True

In [54]:
var = tfe.Variable(10)
var.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=5>

In [57]:
var.assign_add(5)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=20>