In [1]:
import tensorflow as tf

In [2]:
from tensorflow.python.

SyntaxError: invalid syntax (<ipython-input-2-f41ba763a664>, line 1)

In [15]:
#use tensorflow goujian shendu xuexi moxing

#dingyile yigeceng()
def model(inputs):
    #goujianle quanlianjieceng
    #tf.layers.Dense(100,activation=tf.nn.relu)
    #tf.layers.Dense(100,activation=tf.nn.sigmoid)
    #return outputs
    
    x = tf.layers.Dense(100,activation=tf.nn.relu)(inputs)
    #x = x.__call__(inputs)
    
    #yougoujianle quanlianjieceng
    x = tf.layers.Dense(100,activation=tf.nn.relu)(x)
    
    #goujianle yige shuchuceng
    #bubaohan softmax ceng de  shenjingwangluo
    logits = tf.layers.Dense(10,activation=None)(x)
    
    return logits
    

In [16]:
with tf.Graph().as_default() as g:

    batch_size = 32
    inputs = tf.placeholder(dtype=tf.float32,shape=[None,784])
    labels = tf.placeholder(dtype=tf.int32,shape=[None])
    
    logits = model(inputs)
    
    #jiaochashang moxing (return jiaochashang)
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(
        labels=labels,
        logits=logits)
    
    loss = tf.reduce_mean(cross_entropy)
    
    #dingyi youhuaqi(tidu xiajiang fa)
    optim = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

    #baocun moxing 
    saver = tf.train.Saver()

In [18]:
with tf.Session(graph=g) as sess:
    #bianliang chushihua
    sess.run(tf.global_variables_initializer())
    for i in range(100):
        imgs,labs = get_data(...)
        _, res_loss = sess.run([optim,loss],feed_dict={
            inputs:imgs,
            labels:labs
        })
        print(res_loss)
        saver.save(sess, './model.ckpt')

NameError: name 'get_data' is not defined

In [ ]:
with tf.Session() as sess:
    tf.saved_model.loader.load(sess,['serve'],'/tmp/save_path')


In [19]:
saver.save??

In [20]:
def map_fn(x,y):
    r_x = tf.not_equal(x,0)
    r_y = y + 1
    return r_x,r_y

In [21]:
inputs = tf.range(3)
labels = tf.zeros(3)

dataset = tf.data.Dataset.from_tensor_slices((inputs, labels))
dataset = dataset.map(map_fn,4)
#dataset = dataset.map(lambda x, y: (tf.not_equal(x, 0), y + 1))    

In [25]:
#tf.py_func()

In [28]:
# 制作假数据样本，共5个样本
inputs = tf.random_normal([5,3])
labels = tf.constant([1,0,1,0,1])

# 步骤一：数据读取，生成一个dataset对象
dataset = tf.data.Dataset.from_tensor_slices((inputs,labels))

# 步骤二：样本处理
dataset = dataset.shuffle(2)  # 进行打乱，打乱时cache为2
dataset = dataset.batch(3)  # 设置批量大小，这里为3

# 步骤三：批量输出
iterator = dataset.make_initializable_iterator()  # 生成迭代器对象
init_op = iterator.initializer
next_batch = iterator.get_next()

with tf.Session() as sess:
    print(sess.run(init_op))
    print(sess.run(next_batch))

None
(array([[-0.8229255 , -1.3848507 , -2.8479288 ],
       [ 0.7130073 , -0.51762736,  2.2607045 ],
       [ 0.65415967, -0.4201504 , -1.444615  ]], dtype=float32), array([0, 1, 1], dtype=int32))


In [36]:
# 制作假数据样本，共5个样本
inputs = tf.random_normal([5,3])
labels = tf.constant([1,0,1,0,1])

# 步骤一：数据读取，生成一个dataset对象
dataset = tf.data.Dataset.from_tensor_slices((inputs,labels))

# 步骤二：样本处理
dataset = dataset.shuffle(6)  # 进行打乱，打乱时cache为2
dataset = dataset.batch(6)  # 设置批量大小，这里为3

# 步骤三：批量输出
iterator = dataset.make_initializable_iterator()  # 生成迭代器对象
init_op = iterator.initializer
next_batch = iterator.get_next()

with tf.Session() as sess:
    print(sess.run(init_op))
    print(sess.run(next_batch))

None
(array([[-2.2672563 ,  0.17254902,  1.3951885 ],
       [ 0.28764167,  0.24571821,  2.1759105 ],
       [-0.5042624 , -0.24933778, -1.4899601 ],
       [ 0.6328232 , -1.9907446 , -2.103649  ],
       [ 0.81827605,  0.11213845, -1.2033423 ]], dtype=float32), array([0, 0, 1, 1, 1], dtype=int32))


In [39]:
inputs = tf.constant([1,2,3,4,5])
dataset = tf.data.Dataset.from_tensor_slices(inputs)

dataset = dataset.shuffle(buffer_size=3)

iterator = dataset.make_initializable_iterator()
init_op = iterator.initializer
next_batch = iterator.get_next()
with tf.Session() as sess:
    print(sess.run(init_op))
    print(sess.run(next_batch))

None
3


In [43]:
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
dataset = dataset.padded_batch(4, padded_shapes=[None])

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

with tf.Session() as sess:
    print(sess.run(next_element))
    print(sess.run(next_element))
    print(sess.run(next_element))

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]
[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]
[[ 8  8  8  8  8  8  8  8  0  0  0]
 [ 9  9  9  9  9  9  9  9  9  0  0]
 [10 10 10 10 10 10 10 10 10 10  0]
 [11 11 11 11 11 11 11 11 11 11 11]]


In [44]:
tf.train.BytesList()
tf.train.Int64List()
tf.train.FloatList()

tf.train.Feature()

tf.train.Features()

tf.train.Example()


In [2]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random_uniform([4]),
    tf.random_uniform([4, 100], maxval=100, dtype=tf.int32)))

In [4]:
print(dataset2)

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>
