In [6]:
import tensorflow as tf

In [4]:
a = tf.constant(1)
a = tf.constant(2)

In [5]:
print(a)
#two but behind
print(a.name)

Tensor("Const_1:0", shape=(), dtype=int32)
Const_1:0


In [6]:
a = tf.constant(1)
a = a + tf.constant(2)
#only need behind

In [7]:
no = tf.no_op(name='no_op')

### print(no)

In [4]:
res_1,res_2,res_3 = tf.split(tf.ones([5,3]),[1,2,2],0,name = 'split')

In [6]:
res_1
res_2
res_3

<tf.Tensor 'split:2' shape=(2, 3) dtype=float32>

In [14]:
with tf.Graph().as_default():
    ope_1 = tf.constant([1,2])
    ope_2 = tf.add([1,2],[3,4],name = 'op_1')
    ope_3 = tf.add([4,2],[3,7],name = 'op_1')
    ope_4 = tf.add([1,4],[6,4],name = 'op_1')

In [16]:
ope_1

<tf.Tensor 'Const:0' shape=(2,) dtype=int32>

In [17]:
ope_2

<tf.Tensor 'op_1:0' shape=(2,) dtype=int32>

In [23]:
ope_3

<tf.Tensor 'op_1_1:0' shape=(2,) dtype=int32>

In [2]:
ope_4

NameError: name 'ope_4' is not defined

In [27]:
g1 = tf.Graph()
with g1.as_default():
    tf.add(3,5,name = 'add')
    tf.multiply(g1.get_tensor_by_name('add:0'),10,name='mul')
with tf.Session(graph=g1) as sess:
    print(sess.run(g1.get_tensor_by_name('mul:0')))
    print(sess.run(g1.get_operation_by_name('mul')))

80
None


In [3]:
op = tf.no_op(name='hello')
print(op.name)

hello


In [7]:
a = tf.constant([1,2,3],name='value')
print(a.name)

value:0


In [12]:
a = tf.add(1, 2) 
print(a)
print(a.name)

Tensor("Add:0", shape=(), dtype=int32)
Add:0


In [13]:
a1 = tf.add(1,2)
a2 = tf.add(2,3)
print(a1.name)
print(a2.name)

Add_1:0
Add_2:0


In [14]:
g1=tf.Graph()
with g1.as_default():
    m = tf.add(1,2,name='add')
    print(m.name)

add:0


In [15]:
g2 = tf.Graph()
with g2.as_default():
    n = tf.add(3,4,name='add')
    print(n.name)

add:0


In [16]:
a = tf.constant([1,2])
print(a)

Tensor("Const_1:0", shape=(2,), dtype=int32)


In [17]:
with tf.Session() as sess:
    res = tf.where(tf.constant([True,True, False]), 
         tf.constant([1,1, 1]), 
         tf.constant([2,2, 2]))
    print(sess.run(res))

[1 1 2]


In [23]:
with tf.Session() as sess:
    t1 = tf.constant([1,-2,100])
    res1 = tf.where(t1>0)
    t2 = tf.constant([-1,2,100])
    res2 = tf.where(t2>0)
    print(sess.run(res1))
    print(sess.run(res2))
    
    g_res = tf.gather_nd(t1,res1)
    print(sess.run(g_res))

[[0]
 [2]]
[[1]
 [2]]
[  1 100]


In [19]:
import numpy as np
t = np.array([1,-2,100])
t[t>0]

array([  1, 100])

In [20]:
print(t>0)

[ True False  True]


In [4]:
def smooth_l1(x):
    less = 0.5*x*x
    otherwise = tf.abs(x) - 0.5
    return tf.where(tf.abs(x)<1,less,otherwise)


In [8]:
with tf.Session() as sess:
    x = tf.constant([-1.,5,0.5])
    result = smooth_l1(x)
    print(sess.run(result))

[0.5   4.5   0.125]


In [7]:
tf.abs??