In [2]:
import tensorflow as tf

In [2]:
b = tf.constant([[True,False],[True,True]])

In [3]:
res = tf.where(b)

In [4]:
res

<tf.Tensor 'Where:0' shape=(?, 2) dtype=int64>

In [5]:
sess =  tf.InteractiveSession()

In [6]:
res.eval()

array([[0, 0],
       [1, 0],
       [1, 1]])

In [7]:
x = tf.Variable(0.)
x_plus_1 = tf.assign_add(x, 1)

with tf.control_dependencies([x_plus_1]):
    y = x

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(y))

0.0
0.0
0.0
0.0
0.0


In [8]:
x = tf.Variable(0.)
x_plus_1 = tf.assign_add(x, 1)

with tf.control_dependencies([x_plus_1]):
    y = tf.identity(x)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(y))

1.0
2.0
3.0
4.0
5.0


In [9]:
a = [1,2,3,4,5]

In [10]:
print(a)

[1, 2, 3, 4, 5]


In [11]:
print(a[0],a[1],a[2],a[3],a[4])

1 2 3 4 5


In [12]:
print(*a)

1 2 3 4 5


In [14]:
*tf.get_collection()

SyntaxError: can't use starred expression here (cell_name, line 4)

In [17]:
import tensorflow.contrib.autograph as ag
#1.12 import tensorflow.python.autograph

In [28]:
@ag.convert()
def cond_test1(cond):
    if cond:
        return tf.constant(1)
    else:
        return tf.constant(0)

In [29]:
cond = tf.Variable(True)
result = cond_test1(cond)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(result))  # >>> 1
    sess.run(cond.assign(False))
    print(sess.run(result))  # >>> 0

1
0


In [30]:
@ag.convert()
def cond_test2(cond):
    if cond>0:
        return tf.constant(1)
    elif cond<0:
        return tf.constant(-1)
    else:
        return tf.constant(0)

In [31]:
def cond(i, n):
    i = tf.Print(i,[i],'cond')
    return i < n

def body(i, n):
    i = i + 1
    i = tf.Print(i,[i],'body')
    return i, n

i = tf.constant(0)
n = tf.constant(10)

result_i, result_n = tf.while_loop(cond, body, [i, n])

with tf.Session() as sess:
    sess.run(result_i)

In [32]:
with tf.Session() as sess:
    res = tf.where(tf.constant([True, False]), 
         tf.constant([1, 1]), 
         tf.constant([2, 2]))
    print(sess.run(res))  # >>> [1, 2]

[1 2]


In [33]:
with tf.Session() as sess:
    res = tf.where(tf.constant([True, False,False]), 
         tf.constant([1, 1,1]), 
         tf.constant([2, 2,2]))
    print(sess.run(res))

[1 2 2]


In [36]:
with tf.Session() as sess:
    res = tf.where(tf.constant([True, False,True]), 
         tf.constant([1, 1,1]), 
         tf.constant([2, 2,2]))
    print(sess.run(res))

[1 2 1]


In [37]:
with tf.Session() as sess:
    res = tf.where(tf.constant([True, False,True]))
    print(sess.run(res))

[[0]
 [2]]


In [38]:
tf.assign_add??

In [41]:
a = [1,2,2]
b = tf.identity(a)
with tf.Session() as sess:
    print(sess.run(b))

[1 2 2]


In [40]:
a

[1, 2, 2]

In [42]:
x = tf.Variable(0)
x_plus_1 = tf.add(x,1)
with tf.control_dependencies([x_plus_1]):
    y = x
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(y))

0
0
0
0
0


In [46]:
x = tf.Variable(1)
x_plus_2 = tf.assign_add(x,2)
with tf.control_dependencies([x_plus_2]):
    y = tf.identity(x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(6):
        print(sess.run(y))

3
5
7
9
11
13


In [48]:
cond = tf.Variable(True)
def true_fn():
    return tf.constant(1)
def false_fn():
    return tf.constant(0)
result = tf.cond(cond,true_fn,false_fn)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(result))
    sess.run(cond.assign(False))
    print(sess.run(result))

1
0


In [49]:
cond = tf.Variable(True)
def true_fn():
    return tf.constant(1)
def false_fn():
    return tf.constant(0)
result = tf.cond(cond,lambda:tf.constant(1),lambda:tf.constant(0))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(result))
    sess.run(cond.assign(False))
    print(sess.run(result))

1
0


In [50]:
def test(x):
    x = tf.convert_to_tensor(x)
    def greater_zero_fn():
        return tf.constant(1)
    def equal_zero_fn():
        return tf.constant(0)
    def less_zero_fn():
        return tf.constant(-1)
    
    less_equal = tf.cond(x<0,lambda:tf.constant(-1),lambda:tf.constant(0))
    result = tf.cond(x>0,lambda:tf.constant(1),lambda:less_equal)
    
    return result

In [55]:
with tf.Session() as sess:
    a = test(tf.Variable(1))
    b = test(0)
    c = test(-1)
    d = test([1])
    
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))

ValueError: Shape must be rank 0 but is rank 1 for 'cond_32/Switch' (op: 'Switch') with input shapes: [1], [1].

In [58]:
def cond(i,n):
    return i<n
def body(i,n):
    i = i+1
    n = i+n
    return i,n

with tf.Session() as sess:
 #   i = tf.constant(3)
  #  n = tf.constant(50)
    result_i,result_n = tf.while_loop(cond,body,[tf.constant(3),tf.constant(50)])
    sess.run(tf.global_variables_initializer())
    print(sess.run(result_i,result_n))

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

In [59]:
def max_num(m,n):
    m = tf.convert_to_tensor(m)
    n = tf.convert_to_tensor(n)
    def max_m(m,n):
        return m
    def max_n(m,n):
        return n
    tf.cond(m>n,max_m,max_n)

In [60]:
import os

In [61]:
os.path.join('root','home')

'root/home'

In [62]:
ls

18.10.22.ipynb                                              signal.c
18.10.29.ipynb                                              TensorFlow/
18-19_tensorflow_homework1.ipynb                            Untitled 1.odt
1.ipynb                                                     virtual/
bintree.c*                                                  virtual1/
cwd.c                                                       virtual2/
Editing Web1_6. 流程控制.md at master · hh1998lm_Web1.html


In [64]:
with open('1.ipynb','r') as f:
    print(f.readline())
    print(f.read())

{

 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    }
   ],
   "source": [
    "a=3\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}



In [65]:
with tf.gfile.GFile('1.ipynb','r') as f:
    print(f.read())

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    }
   ],
   "source": [
    "a=3\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}



In [71]:
with tf.gfile.FastGFile('1.ipynb','r') as f:
   # print(f.read())
    print(f.read(8))
    print(f.read(10))
    f.seek(0)
    print(f.read(8))

{
 "cell
s": [
  {

{
 "cell


In [72]:
#'train_[0-9].jpg'

In [73]:
TensorArray??

Object `TensorArray` not found.


In [3]:
with tf.gfile.FastGFile('1.ipynb','r') as f:
    print(f.read())

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    }
   ],
   "source": [
    "a=3\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}



In [4]:
with tf.gfile.FastGFile('1.ipynb','r') as f:
    print(f.read(8))
    
    print(f.read())

{
 "cell
s": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n"
     ]
    }
   ],
   "source": [
    "a=3\n",
    "print(a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}



In [13]:
with tf.Graph().as_default() as g:
    add_t = tf.add(1,2)
    result = tf.multiply(add_t,5)
    
    sg = g.as_graph_def()
    print(sg)

node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "Add/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Add/x"
  input: "Add/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Mul/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 5
      }
    }
  }
}
node {
  name: "Mul"
  op: "Mul"
  input: "Add"
  input: "Mul/y"
  attr {
    key: "T"
    value {
  

In [6]:
with tf.Session() as sess:
    print(sess.run(a))

[1 2]


In [21]:
with tf.variable_scope('scope',reuse=True) as scope:
    b = tf.get_variable('var',dtype=tf.float32,shape=[])
    print(b.name)
    
    scope.reuse_variables()
    var = tf.get_variable('var')

scope/var:0


In [1]:
def max_num(m,n):
    m = tf.convert_to_tensor(m)
    n = tf.convert_to_tensor(n)
    def max_m(m,n):
        return m
    def max_n(m,n):
        return n
    tf.cond(m>n,max_m,max_n)

In [3]:
tf.TensorArray??

In [4]:
import tensorflow as tf

def condition(time, output_ta_l): 
    return tf.less(time, 3)

def body(time, output_ta_l): 
    output_ta_l = output_ta_l.write(time, [2.4, 3.5]) 
    return time + 1, output_ta_l

time = tf.constant(0) 
output_ta = tf.TensorArray(dtype=tf.float32, size=1, dynamic_size=True)

result = tf.while_loop(condition, body, loop_vars=[time, output_ta])

last_time, last_out = result

final_out = last_out.stack()

with tf.Session(): 
    print(last_time.eval()) 
    print(final_out.eval())

3
[[2.4 3.5]
 [2.4 3.5]
 [2.4 3.5]]
