In [2]:
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target
#with tf.Session() as sess:
 #   sess.run(tf.global_variables_initializer())
  #  print(sess.run(X))
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
#将鸢尾花数据集安装8 : 2的比例划分成训练集与验证集
Xtrain, Xtest, Ytrain, Ytest = train_test_split(
    iris.data, iris.target, test_size=0.2,random_state=0)
print(Xtrain.shape)
print(Xtest.shape)

(120, 4)
(30, 4)


In [7]:
#tf.arg_min??
#tf.argmin（）返回矩阵横列或者纵列的最小值的坐标，取决于第二个参数 
#tf.argmin(
#    input,
 #   axis=None,//0是纵列 1是横列
  #  name=None,
   # dimension=None,
    #output_type=tf.int64
#)
x = tf.constant([[0, 2, 1], [2, 1, 3]]) 
sess = tf.Session() 
print(sess.run(tf.argmin(x, 0)))
print(sess.run(tf.argmin(x, 1)))


[0 1 0]
[0 1]


In [8]:
#tf.nn.top_k
k=2
a = tf.constant([3, 4, -1, 6]) 
size_a = tf.size(a) 
max_index = tf.nn.top_k(a, k)[1]
min_index = tf.nn.top_k(-a, k)[1]
sess = tf.Session() 
idx_max, idx_min = sess.run([max_index, min_index]) 
print(idx_max, idx_min)


[3 1] [2 0]


In [58]:
#设计K近邻模型
tf.sqrt?

In [10]:
with tf.Session() as sess:
    for i in range(150):
        for j in range(150):
            a = tf.add(X[i],tf.negative(X[j]))
            b = tf.square(a)
            c = tf.reduce_sum(b,1)
            dis = tf.sqrt(c)
            print(sess.run(a))
          #  print(sess.run(b))
#            distance = tf.sqrt(tf.reduce_sum(tf.square(tf.add(X[i],tf.negative(X[j]))),1))
            
        #distance_total = tf.reduce_sum(distance,reduction_indices=1)
       # print(sess.run(distance))

ValueError: Invalid reduction dimension 1 for input with 1 dimensions. for 'Sum_2' (op: 'Sum') with input shapes: [4], [] and with computed input tensors: input[1] = <1>.

In [52]:
k = 10
a = tf.constant(distance_total)
max_index = tf.nn.top_k(a, k)[1]
min_index = tf.nn.top_k(-a, k)[1]
sess = tf.Session() 
idx_max, idx_min = sess.run([max_index, min_index]) 
print(idx_max, idx_min)

NameError: name 'distance_total' is not defined

In [38]:
#reduce_sum应该理解为压缩求和，用于降维
with tf.Session() as sess:
    x = [[1,1,2],[1,3,4]]
    #求和
    print(sess.run(tf.reduce_sum(x)))
    #按列求和
    print(sess.run(tf.reduce_sum(x,0)))
    #按行求和
    print(sess.run(tf.reduce_sum(x,1)))
    #按照行的维度求和
    print(sess.run(tf.reduce_sum(x,1,keep_dims=True)))
    #行列求和
    print(sess.run(tf.reduce_sum(x,[0,1])))
    #reduction_indices:在哪一维上求解,0列,1行

12
[2 4 6]
[4 8]
[[4]
 [8]]
12


In [25]:
# 输入占位符
xtr = tf.placeholder(tf.float32,shape=[120,4])
xte = tf.placeholder(tf.float32,shape=[30,4])


# 计算L1距离
#tf.abs(sqrt)
#tf.negative(-)
distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.negative(xtr))), reduction_indices=1)
# 获取最小距离的索引
pred = tf.arg_min(distance, 0)

#分类精确度
accuracy = 0.

# 初始化变量
init = tf.global_variables_initializer()


# 运行会话，训练模型
with tf.Session() as sess:

    # 运行初始化
    sess.run(init)

    # 遍历测试数据
    for i in range(len(Xtest)):
        # 获取当前样本的最近邻索引
        nn_index = sess.run(pred, feed_dict={xtr: Xtrain, xte: Xtest[i, :]})   #向占位符传入训练数据
        # 最近邻分类标签与真实标签比较
        print("Test", i, "Prediction:", np.argmax(Ytr[nn_index]), \
            "True Class:", np.argmax(Ytest[i]))
        # 计算精确度
        if np.argmax(Ytrain[nn_index]) == np.argmax(Ytest[i]):
            accuracy += 1./len(Xtest)

    print("Done!")
    print("Accuracy:", accuracy)

ValueError: Cannot feed value of shape (4,) for Tensor 'Placeholder_9:0', which has shape '(30, 4)'