In [1]:
import tensorflow as tf
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target
#with tf.Session() as sess:
 #   sess.run(tf.global_variables_initializer())
  #  print(sess.run(X))
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
#将鸢尾花数据集安装8 : 2的比例划分成训练集与验证集
Xtrain, Xtest, Ytrain, Ytest = train_test_split(
    iris.data, iris.target, test_size=0.2,random_state=0)
print(Xtrain.shape)
print(Xtest.shape)

(120, 4)
(30, 4)


In [5]:
#tf.arg_min??
#tf.argmin（）返回矩阵横列或者纵列的最小值的坐标，取决于第二个参数 
#tf.argmin(
#    input,
 #   axis=None,//0是纵列 1是横列
  #  name=None,
   # dimension=None,
    #output_type=tf.int64
#)distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.negative(xte)))

# 输入占位符
a = tf.placeholder("float")
b = tf.placeholder("float")


In [6]:
#计算L1距离
for i in range(120):
    distance = tf.reduce_sum(tf.abs(tf.add(Xtrain[i], tf.negative(Xtrain))),reduction_indices=1)
    print(Ytrain[i])
#设计K近邻模型
size_a = tf.size(distance)
k=20
min_index = tf.nn.top_k(-distance,size_a)[1]
with tf.Session() as sess:
    for j in range(20):
#        print(sess.run(distance[min_index[j]]))
        y[min_index[j]] = Ytrain[i]
        print(sess.run(min_index[j]))
        print(sess.run(y[min_index[j]]))

2
1
0
2
2
1
0
1
1
1
2
0
2
0
0
1
2
2
2
2
1
2
1
1
2
2
2
2
1
2
1
0
2
1
1
1
1
2
0
0
2
1
0
0
1
0
2
1
0
1
2
1
0
2
2
2
2
0
0
2
2
0
2
0
2
2
0
0
2
0
0
0
1
2
2
0
0
0
1
1
0
0
1
0
2
1
2
1
0
2
0
2
0
0
2
0
2
1
1
1
2
2
1
1
0
1
2
2
0
1
1
1
1
0
0
0
2
1
2
0


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [7]:
init = tf.global_variables_initializer()


In [8]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(len(Xtest)):
        pred_index = sess.run(pred,feed_dict={a:Xtrain,b:Xtest[i,:]})
        print("test",i,"prediction",np.argmax(Ytest[pred_index]),"True Class:",np.argmax(Ytest[i]))

NameError: name 'pred' is not defined

In [21]:
import numpy as np
import  os
import  tensorflow as tf
from sklearn import datasets

#将鸢尾花数据集安装8 : 2的比例划分成训练集与验证集
Xtrain, Xtest, Ytrain, Ytest = train_test_split(
    iris.data, iris.target, test_size=0.2,random_state=0)

# 计算图输入占位符
#train 使用全部样本，test 逐个样本进行测试
xtrain=tf.placeholder("float",[120,4])#图片训练集
xtest=tf.placeholder("float",[4])#测试集

#使用L1距离进行最近邻计算
#计算L1距离
distance=tf.reduce_sum(tf.abs(tf.add(xtrain,tf.negative(xtest))),axis=1)
# 预测: 获得最小距离的索引 (根据最近邻的类标签进行判断)
pred = tf.arg_min(distance, 0)


In [27]:
#评估正确率
accuracy=0
# 初始化节点
init = tf.global_variables_initializer()
#启动会话
with tf.Session() as sess:
    sess.run(init)
    test_num=len(Xtest)#测试样本的数量
    for i in range(test_num):
      # 获取当前测试样本的最近邻
        nn_index = sess.run(pred, feed_dict={xtrain: Xtrain, xtest: Xtest[i]})#一个样本一个样本的输入
      # 获得最近邻预测标签，然后与真实的类标签比较，由于是 one_hot 编码，所以要用 argmax 将类标取出
        pred_label = np.argmax(Ytrain[nn_index])
        true_label = np.argmax(Ytest[i])
        print("Test", i, "Predicted Label:", pred_label,
          "True Label:", true_label)
          # 计算准确率
        if pred_class_label == true_class_label:
            accuracy += 1
 
    print("Done!")
    accuracy /=test_num
    print("Accuracy:", accuracy)

Test 0 Predicted Label: 0 True Label: 0
Test 1 Predicted Label: 0 True Label: 0
Test 2 Predicted Label: 0 True Label: 0
Test 3 Predicted Label: 0 True Label: 0
Test 4 Predicted Label: 0 True Label: 0
Test 5 Predicted Label: 0 True Label: 0
Test 6 Predicted Label: 0 True Label: 0
Test 7 Predicted Label: 0 True Label: 0
Test 8 Predicted Label: 0 True Label: 0
Test 9 Predicted Label: 0 True Label: 0
Test 10 Predicted Label: 0 True Label: 0
Test 11 Predicted Label: 0 True Label: 0
Test 12 Predicted Label: 0 True Label: 0
Test 13 Predicted Label: 0 True Label: 0
Test 14 Predicted Label: 0 True Label: 0
Test 15 Predicted Label: 0 True Label: 0
Test 16 Predicted Label: 0 True Label: 0
Test 17 Predicted Label: 0 True Label: 0
Test 18 Predicted Label: 0 True Label: 0
Test 19 Predicted Label: 0 True Label: 0
Test 20 Predicted Label: 0 True Label: 0
Test 21 Predicted Label: 0 True Label: 0
Test 22 Predicted Label: 0 True Label: 0
Test 23 Predicted Label: 0 True Label: 0
Test 24 Predicted Label: 0

In [10]:
k = 10
a = tf.constant(distance_total)
max_index = tf.nn.top_k(a, k)[1]
min_index = tf.nn.top_k(-a, k)[1]
sess = tf.Session() 
idx_max, idx_min = sess.run([max_index, min_index]) 
print(idx_max, idx_min)

NameError: name 'distance_total' is not defined

In [11]:
#reduce_sum应该理解为压缩求和，用于降维
with tf.Session() as sess:
    x = [[1,1,2],[1,3,4]]
    #求和
    print(sess.run(tf.reduce_sum(x)))
    #按列求和
    print(sess.run(tf.reduce_sum(x,0)))
    #按行求和
    print(sess.run(tf.reduce_sum(x,1)))
    #按照行的维度求和
    print(sess.run(tf.reduce_sum(x,1,keep_dims=True)))
    #行列求和
    print(sess.run(tf.reduce_sum(x,[0,1])))
    #reduction_indices:在哪一维上求解,0列,1行

12
[2 4 6]
[4 8]
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[[4]
 [8]]
12


In [12]:
# 输入占位符
xtr = tf.placeholder(tf.float32,shape=[120,4])
xte = tf.placeholder(tf.float32,shape=[30,4])


# 计算L1距离
#tf.abs(sqrt)
#tf.negative(-)
distance = tf.reduce_sum(tf.abs(tf.add(xtr, tf.negative(xtr))), reduction_indices=1)
# 获取最小距离的索引
pred = tf.arg_min(distance, 0)

#分类精确度
accuracy = 0.

# 初始化变量
init = tf.global_variables_initializer()


# 运行会话，训练模型
with tf.Session() as sess:

    # 运行初始化
    sess.run(init)

    # 遍历测试数据
    for i in range(len(Xtest)):
        # 获取当前样本的最近邻索引
        nn_index = sess.run(pred, feed_dict={xtr: Xtrain, xte: Xtest[i, :]})   #向占位符传入训练数据
        # 最近邻分类标签与真实标签比较
        print("Test", i, "Prediction:", np.argmax(Ytr[nn_index]), \
            "True Class:", np.argmax(Ytest[i]))
        # 计算精确度
        if np.argmax(Ytrain[nn_index]) == np.argmax(Ytest[i]):
            accuracy += 1./len(Xtest)

    print("Done!")
    print("Accuracy:", accuracy)

Instructions for updating:
Use `argmin` instead


ValueError: Cannot feed value of shape (4,) for Tensor 'Placeholder_1:0', which has shape '(30, 4)'